import { QUESTION_BANK } from "../constants/questions";

// ---------------------------------------------------------------------------
// MOCK AI INTERVIEWER
// This is the dev-mode / fallback implementation described in the project
// brief: a scripted follow-up tree per difficulty, not a real LLM call.
// Swap buildScript()/generateFeedback() for real API calls behind this same
// module boundary when a real provider (e.g. ANTHROPIC_API_KEY) is wired up —
// nothing outside this file needs to change.
// ---------------------------------------------------------------------------

// Builds the ordered list of AI turns + "wait for the user" pauses for a
// given difficulty. useInterviewEngine walks through this array.
//
// aiQuestions (Phase 3.1): an array of { question, skill } generated by
// the backend's Gemini-backed service, used as the follow-up question
// text in place of the old hardcoded QUESTION_BANK follow-ups. The local
// follow-ups remain as a fallback only — this function is never called
// without aiQuestions in normal operation once the interview room has
// them (see useInterviewEngine).
export function buildScript(difficulty, aiQuestions, meta = {}) {
  const q = QUESTION_BANK[difficulty.toLowerCase()];
  // For a company-targeted interview, acknowledge the target in the
  // opening line so the room's interviewer visibly knows the context.
  // Empty for custom / older interviews — the rest of the script is
  // identical either way.
  const { company, position } = meta;
  const targetLine = company
    ? ` This one's set up as prep for ${company}${position ? ` (${position})` : ""}, so I'll pitch it at that bar.`
    : "";
  const lines = [
    { ai: `Hi, welcome to your ${difficulty.toLowerCase()} DSA interview.${targetLine} We'll work through one problem together, and I'll be asking follow-ups as we go. Ready to start?` },
    { waitUser: true },
    { ai: `Great. Here's the problem: "${q.title}." ${q.statement}` },
    { waitUser: true },
  ];
  const followUps = aiQuestions?.length ? aiQuestions.map((item) => item.question) : q.followUps;
  followUps.forEach((f) => {
    lines.push({ ai: f });
    lines.push({ waitUser: true });
  });
  lines.push({ ai: "Good work — that's a wrap on this problem. Take a breath, we're done here. Click 'End interview' when you're ready to see your feedback." });
  return lines;
}

// Speaks a line using the browser's built-in speech synthesis.
// Degrades silently to text-only if unsupported (e.g. some browsers/embeds).
export function speak(text) {
  try {
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 1.02;
      utterance.pitch = 1.0;
      window.speechSynthesis.speak(utterance);
    }
  } catch (e) {
    /* speech synthesis unavailable — silently degrade to text-only */
  }
}

export function stopSpeaking() {
  window.speechSynthesis?.cancel();
}

// DEPRECATED (Phase 3.5). The visible interview result now comes from the
// backend's authoritative final report (GET/POST /interviews/:id/report),
// which aggregates the real Phase 3.3 per-question evaluations. This
// word-count/regex heuristic fabricated non-zero scores even when the
// candidate never answered — it is no longer called anywhere. Kept only
// so the module boundary and history are intact; delete once nothing in
// the tree references it.
export function generateFeedback(session) {
  const userMsgs = session.messages.filter((m) => m.from === "user");
  const totalWords = userMsgs.reduce((a, m) => a + m.text.split(/\s+/).length, 0);
  const avgWords = totalWords / (userMsgs.length || 1);
  const mentionsComplexity = userMsgs.some((m) => /o\(|log|complexity|time|space/i.test(m.text));
  const mentionsEdge = userMsgs.some((m) => /edge|empty|null|zero|duplicate/i.test(m.text));
  const answered = userMsgs.filter((m) => m.text.length > 15).length;

  const clamp = (n) => Math.max(30, Math.min(97, Math.round(n)));
  const base = clamp(45 + avgWords * 1.4 + answered * 4);

  const categories = [
    { label: "Problem solving", score: clamp(base + (answered >= 3 ? 6 : -6)) },
    { label: "Data structures knowledge", score: clamp(base - 2) },
    { label: "Algorithmic thinking", score: clamp(base + (mentionsComplexity ? 8 : -8)) },
    { label: "Code quality", score: clamp(base - 4) },
    { label: "Time complexity", score: clamp(mentionsComplexity ? base + 10 : base - 15) },
    { label: "Space complexity", score: clamp(mentionsComplexity ? base + 4 : base - 12) },
    { label: "Communication", score: clamp(base + (avgWords > 12 ? 8 : -6)) },
    { label: "Confidence", score: clamp(base + (avgWords > 8 ? 4 : -4)) },
    { label: "Handling follow-ups", score: clamp(base + (answered >= 4 ? 6 : -6)) },
  ];
  const overall = clamp(categories.reduce((a, c) => a + c.score, 0) / categories.length);

  const strengths = [];
  const weaknesses = [];
  if (mentionsComplexity) strengths.push("You proactively discussed time/space complexity without being asked twice.");
  else weaknesses.push("Complexity analysis was thin — state Big-O for every approach you propose, even unprompted.");
  if (mentionsEdge) strengths.push("You considered edge cases (empty input, duplicates) on your own.");
  else weaknesses.push("Edge cases weren't addressed — always narrate empty/null/duplicate scenarios before you finish.");
  if (avgWords > 12) strengths.push("Your explanations were detailed enough for an interviewer to follow your reasoning.");
  else weaknesses.push("Answers were quite short — narrate your thinking out loud, not just the final answer.");
  if (answered >= 4) strengths.push("You stayed engaged through every follow-up instead of giving one-line answers.");

  return {
    overall,
    categories,
    strengths: strengths.length ? strengths : ["You completed the full interview flow."],
    weaknesses: weaknesses.length ? weaknesses : ["No major gaps detected in this mock run."],
    summary: `You worked through "${session.q.title}" at ${session.config.difficulty} difficulty. ${
      overall >= 75
        ? "Strong round overall — your reasoning was clear and you handled follow-ups well."
        : overall >= 50
        ? "A solid attempt with room to tighten up complexity analysis and edge-case coverage."
        : "This one was rough — the fundamentals are there, but slow down and narrate your thinking more."
    }`,
    nextTopics: overall >= 75 ? ["Graphs & BFS/DFS", "Dynamic programming"] : ["Big-O fundamentals", "Two-pointer & sliding window patterns"],
  };
}
